kind: Model
apiVersion: v1alpha3
metadata:
  displayName: Urban Development Model (v04)
  name: open-udm-v04
  summary: Model the potential areas of urban development given a set of contraints and attractors.
  description: >
    The model uses optimisation of a set of attractors to urban development and constraints for urban development to predict the given projected demand and development parameters where urban development will take place.
  type: testing
spec:
  inputs:
    env:
      - name: MINIMUM_DEVELOPMENT_AREA
        title: Minum development area size
        desc: The minimum size of area for development
        type: integer
        default: 100
        min: 1
        max: 1000
