version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run: python setup.py build
      - run: python setup.py install
      - run: python scripts/udm_solo.py

      - setup_remote_docker:
                docker_layer_caching:

      #- run: |
          #docker build -t rsenucitycat.azurecr.io/city-cat-configuration-service:latest -t rsenucitycat.azurecr.io/city-cat-configuration-service:$CIRCLE_SHA1 .
          #docker login -u $DOCKER_USER -p $DOCKER_PASS rsenucitycat.azurecr.io
          #docker push rsenucitycat.azurecr.io/city-cat-configuration-service:latest
          #docker push rsenucitycat.azurecr.io/city-cat-configuration-service:$CIRCLE_SHA1

      - save_cache:
          paths:
              - ".venv"
              - "/usr/local/bin"
              - "/usr/local/lib/python3.6/site-packages"
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

#workflows:
  #version: 2
  #build:
    #jobs:
      #- build:
          #context: citycat
